import type { ServiceRequest } from "@/lib/domain/types";
import { demoProvider } from "./demo-provider";
import type {
  AIProvider,
  AssistBundle,
  CustomerReply,
  IntakeSummary,
  ReplyChannel,
  TechNotes,
} from "./provider";

/**
 * LiveAIProvider — talks to `/api/ai`, which holds the credential server-side.
 *
 * Every method degrades to the demo engine on any failure (no key, network
 * error, malformed response). The demo must never break because a model call
 * failed, so the fallback is the default, not the exception path.
 */
export class LiveAIProvider implements AIProvider {
  readonly id = "live" as const;
  readonly label = "Live model";
  readonly description =
    "Generated by a hosted model from the structured intake answers. The API key stays on the server.";

  private cache = new Map<string, Promise<AssistBundle>>();

  constructor(private readonly endpoint = "/api/ai") {}

  /** The structured summary is deterministic by design — it isn't model output. */
  async summarize(request: ServiceRequest): Promise<IntakeSummary> {
    return demoProvider.summarize(request);
  }

  async callSummary(request: ServiceRequest): Promise<string> {
    return (await this.assist(request, "email")).callSummary;
  }

  async reply(request: ServiceRequest, channel: ReplyChannel): Promise<CustomerReply> {
    return (await this.assist(request, channel)).reply;
  }

  async techNotes(request: ServiceRequest): Promise<TechNotes> {
    return (await this.assist(request, "email")).techNotes;
  }

  async assist(request: ServiceRequest, channel: ReplyChannel): Promise<AssistBundle> {
    const key = `${request.id}:${request.updatedAt}:${channel}`;
    const cached = this.cache.get(key);
    if (cached) return cached;
    const pending = this.fetchAssist(request, channel);
    this.cache.set(key, pending);
    return pending;
  }

  private async fetchAssist(
    request: ServiceRequest,
    channel: ReplyChannel,
  ): Promise<AssistBundle> {
    try {
      const res = await fetch(this.endpoint, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ request, channel }),
      });
      if (!res.ok) throw new Error(`AI endpoint responded ${res.status}`);
      const data = (await res.json()) as {
        callSummary: string;
        replySubject: string;
        replyBody: string;
        techNotes: TechNotes;
      };
      return {
        callSummary: data.callSummary,
        reply: {
          channel,
          subject: channel === "email" ? data.replySubject : undefined,
          body: data.replyBody,
        },
        techNotes: data.techNotes,
      };
    } catch {
      return demoProvider.assist(request, channel);
    }
  }
}
